server:
  port: 8081

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ecom
    username: ecom
    password: ecom

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_schema: product_schema

  flyway:
    enabled: true
    schemas: product_schema
    repair-on-migrate: true
    clean-disabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,threaddump,heapdump,env,configprops
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317   # for local IntelliJ runs (Tempo in Docker -> use localhost if you port-map)

logging:
  file:
    name: logs/product-service.json
  level:
    root: INFO